/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DipeshbotRouteImport } from './routes/dipeshbot'
import { Route as IndexRouteImport } from './routes/index'

const DipeshbotRoute = DipeshbotRouteImport.update({
  id: '/dipeshbot',
  path: '/dipeshbot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dipeshbot': typeof DipeshbotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dipeshbot': typeof DipeshbotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dipeshbot': typeof DipeshbotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dipeshbot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dipeshbot'
  id: '__root__' | '/' | '/dipeshbot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DipeshbotRoute: typeof DipeshbotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dipeshbot': {
      id: '/dipeshbot'
      path: '/dipeshbot'
      fullPath: '/dipeshbot'
      preLoaderRoute: typeof DipeshbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DipeshbotRoute: DipeshbotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
